Que 1 :-
Planning a Data Science Project
- Choose a small dataset (e.g., Titanic survival, Iris dataset).
- Write down the project goal in plain English.
- Create a data science pipeline (using a dictionary or list in Python) that shows
each step.
- Print out the sequence as a checklist for the project.

In [4]:
#Data Select Titanic survival

# Project Goal
goal = "Predict whether a passenger survives or not"

# Data Science Pipeline
pipeline = [
    "Load dataset",
    "Clean data",
    "Handle missing values",
    "Encode categorical data",
    "Select important features",
    "Split data into train and test",
    "Train machine learning model",
    "Evaluate model performance"
]

# Print checklist
print("Project Goal:", goal)
print("\nPipeline Steps:")
for step in pipeline:
    print("-", step)

Project Goal: Predict whether a passenger survives or not

Pipeline Steps:
- Load dataset
- Clean data
- Handle missing values
- Encode categorical data
- Select important features
- Split data into train and test
- Train machine learning model
- Evaluate model performance


Que 2 :- Framing a Machine Learning Problem
- Select any dataset (e.g., Diabetes, Titanic).
- Define:|
What is the input (features)?
- What is the output (target)?
What kind of ML problem is this?
- Write a small Python dictionary that describes the problem structure:
"Dataset": "Titanic",
"Features": ["Age", "Gender", "Fare", "Class"].
"Target": "Survived",
"ML _Type": "Classification"

In [5]:
problem = {
    "Dataset": "Titanic",
    "Features": ["Age", "Gender", "Fare", "Class"],
    "Target": "Survived",
    "ML_Type": "Classification"
}

print(problem)

{'Dataset': 'Titanic', 'Features': ['Age', 'Gender', 'Fare', 'Class'], 'Target': 'Survived', 'ML_Type': 'Classification'}


Que 3:- Tensors
- Create a scalar, vector, matrix, and 3D tensor in Pandas and PyTorch.
- Print their shapes and dimensions.

In [5]:
import pandas as pd
import torch 

#Scalar 
scalar = torch.tensor(5)

#Vector (1D)
vector = torch.tensor([1, 2, 3])

#Matrix (2D)
matrix = torch.tensor([[1, 2], [3, 4]])

# 3D Tensor 
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Print shapes
print("Scalar shape:", scalar.shape)
print("Vector shape:", vector.shape)
print("Matrix shape:", matrix.shape)
print("3D Tensor shape:", tensor_3d.shape)

# Dimensions
print("\nDimensions:")
print("Scalar dim:", scalar.dim())
print("Vector dim:", vector.dim())
print("Matrix dim:", matrix.dim())
print("3D Tensor dim:", tensor_3d.dim())

Scalar shape: torch.Size([])
Vector shape: torch.Size([3])
Matrix shape: torch.Size([2, 2])
3D Tensor shape: torch.Size([2, 2, 2])

Dimensions:
Scalar dim: 0
Vector dim: 1
Matrix dim: 2
3D Tensor dim: 3


Que 4:- Tensors
- Generate a random tensor (shape = (3,3,3)).
Perform:
- Reshape to (9,3).
Slice out the first two "layers".
- Matrix multiplication between two 2D tensors.
- Demonstrate broadcasting with two tensors of shapes (3,1) and (3,3).

In [16]:
#Create tensor 
x= torch.tensor([[1, 2, 3], [4, 5, 6]])

#Reshaping
reshaped = x.reshape(3,2)
print("Reshaped:\n", reshaped)

#Slicing 
slice_part = x[:, 1]
print("\nSliced:\n", slice_part)

#Broadcasting
y = torch.tensor([10, 20, 30])
result = x + y
print("\nBroadcasting Result:\n", result)

Reshaped:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Sliced:
 tensor([2, 5])

Broadcasting Result:
 tensor([[11, 22, 33],
        [14, 25, 36]])
